# Site settings
title: Jaden Harnar
email: jharnar@vivaldi.net
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://vatvo.github.io # the base hostname & protocol for your site

# Build settings
markdown: kramdown
